Change init scripts so that they can be reused by core

diff --git a/bin/hubshell b/bin/hubshell
--- a/bin/hubshell
+++ b/bin/hubshell
@@ -2,16 +2,33 @@
 
 set -e
 
-USAGE="Usage: $0
+SHELL_PATH=src/mist/api/hub/shell.py
+
+USAGE="Usage: $0 [-h] [-s <SHELL_PATH>]
 
 Start hub-shell
+
+Options:
+    -h              Show this help message and exit.
+    -s <SHELL_PATH> Hubshell file path. Defaults to $SHELL_PATH.
 "
 
-if [ "$1" = "-h" ]; then
-    echo "$USAGE"
-    exit
-fi
+while getopts "hs:" opt; do
+    case "$opt" in
+        h)
+            echo "$USAGE"
+            exit
+            ;;
+        s)
+            SHELL_PATH=$OPTARG
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            echo "$USAGE" >&2
+            exit 1
+    esac
+done
 
 set -x
 
-exec python src/mist/api/hub/shell.py server
+exec python $SHELL_PATH server
diff --git a/bin/poller b/bin/poller
--- a/bin/poller
+++ b/bin/poller
@@ -2,20 +2,42 @@
 
 set -e
 
-USAGE="Usage: $0
+LOGLEVEL="INFO"
+TASKS="mist.api.tasks"
+
+USAGE="Usage: $0 [-h] [-l <LOGLEVEL>] [-t <TASKS_PATH>]
 
 Start poller
+
+Options:
+    -h              Show this help message and exit.
+    -l <LOGLEVEL>   Log level. Defaults to $LOGLEVEL.
+    -t <TASKS_PATH> Tasks file to import. Defaults to $TASKS.
 "
 
-if [ "$1" = "-h" ]; then
-    echo "$USAGE"
-    exit
-fi
+while getopts "hl:t:" opt; do
+    case "$opt" in
+        h)
+            echo "$USAGE"
+            exit
+            ;;
+        l)
+            LOGLEVEL=$OPTARG
+            ;;
+        t)
+            TASKS=$OPTARG
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            echo "$USAGE" >&2
+            exit 1
+    esac
+done
 
 set -x
 
 exec celery beat \
-    -A mist.api.tasks \
+    -A $TASKS \
     -S mist.api.poller.schedulers.PollingScheduler \
-    -l INFO \
+    -l $LOGLEVEL \
     --pidfile=/var/run/poller.pid
